server:
  port: 8080
  tomcat.max-threads: 2
  tomcat.uri-encoding: UTF-8
  servlet:
    session:
      timeout: 30m

spring:
  datasource:
    url: jdbc:mysql://49.233.130.58:3306/netdisk?useUnicode=true&characterEncoding=utf8
    username: db_user
    password: db_user[AT]milkyship
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    database: MYSQL
    show-sql: true

FileIO:
  HashBreakLength: 4
  FileRootPath: File:///NetDiskFile/
